/* Autogenerated by png2wx.pl on Sun Nov 12 12:02:05 2017 */
#ifndef ICONS_H
#define ICONS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *_img_deviation_pi;
extern wxBitmap *_img_deviation;
extern wxBitmap *_img_logoOpenCPN;

#endif /* ICONS_H */
